name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  audioplayers: ^6.5.0
  chewie: ^1.12.1
  file_picker: ^10.2.1
  flutter:
    sdk: flutter
  lottie: ^3.3.1
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/motions/

